champs = [
    "Aatrox",
    "Ahri",
    "Akali",
    "Alistar",
    "Amumu",
    "Anivia",
    "Annie",
    "Aphelios",
    "Ashe",
    "Aurelion Sol",
    "Azir",
    "Bard",
    "Blitzcrank",
    "Brand",
    "Braum",
    "Caitlyn",
    "Camille",
    "Cassiopeia",
    "Cho'Gath",
    "Corki",
    "Darius",
    "Diana",
    "Dr. Mundo",
    "Draven",
    "Ekko",
    "Elise",
    "Evelynn",
    "Ezreal",
    "Fiddlesticks",
    "Fiora",
    "Fizz",
    "Galio",
    "Gangplank",
    "Garen",
    "Gnar",
    "Gragas",
    "Graves",
    "Hecarim",
    "Heimerdinger",
    "Illaoi",
    "Irelia",
    "Ivern",
    "Janna",
    "Jarvan IV",
    "Jax",
    "Jayce",
    "Jhin",
    "Jinx",
    "Kai'Sa",
    "Kalista",
    "Karma",
    "Karthus",
    "Kassadin",
    "Katarina",
    "Kayle",
    "Kayn",
    "Kennen",
    "Kha'Zix",
    "Kindred",
    "Kled",
    "Kog'Maw",
    "LeBlanc",
    "Lee Sin",
    "Leona",
    "Lillia",
    "Lissandra",
    "Lucian",
    "Lulu",
    "Lux",
    "Malphite",
    "Malzahar",
    "Maokai",
    "Master Yi",
    "Miss Fortune",
    "Mordekaiser",
    "Morgana",
    "Nami",
    "Nasus",
    "Nautilus",
    "Neeko",
    "Nidalee",
    "Nocturne",
    "Nunu & Willump",
    "Olaf",
    "Orianna",
    "Ornn",
    "Pantheon",
    "Poppy",
    "Pyke",
    "Qiyana",
    "Quinn",
    "Rakan",
    "Rammus",
    "Rek'Sai",
    "Rell",
    "Renekton",
    "Rengar",
    "Riven",
    "Rumble",
    "Ryze",
    "Samira",
    "Sejuani",
    "Senna",
    "Seraphine",
    "Sett",
    "Shaco",
    "Shen",
    "Shyvana",
    "Singed",
    "Sion",
    "Sivir",
    "Skarner",
    "Sona",
    "Soraka",
    "Swain",
    "Sylas",
    "Syndra",
    "Tahm Kench",
    "Taliyah",
    "Talon",
    "Taric",
    "Teemo",
    "Thresh",
    "Tristana",
    "Trundle",
    "Tryndamere",
    "Twisted Fate",
    "Twitch",
    "Udyr",
    "Urgot",
    "Varus",
    "Vayne",
    "Veigar",
    "Vel'Koz",
    "Vi",
    "Viego",
    "Viktor",
    "Vladimir",
    "Volibear",
    "Warwick",
    "Wukong",
    "Xayah",
    "Xerath",
    "Xin Zhao",
    "Yasuo",
    "Yone",
    "Yorick",
    "Yuumi"
]
roless=[
    "Top",
    "Mid",
    "Mid Top",
    "Support",
    "Jungle Support",
    "Mid",
    "Mid Support",
    "ADC",
    "ADC Support",
    "Mid",
    "Mid",
    "Support",
    "Support",
    "Support Mid",
    "Support",
    "ADC",
    "Top Jungle",
    "Mid",
    "Top Mid",
    "Mid ADC",
    "Top",
    "Jungle Mid",
    "Top Jungle",
    "ADC",
    "Jungle Mid",
    "Jungle",
    "Jungle",
    "ADC Mid",
    "Jungle Support",
    "Top",
    "Mid",
    "Mid Support",
    "Top Mid",
    "Top",
    "Top",
    "Jungle Mid Top Support",
    "Jungle",
    "Jungle Top",
    "Mid Top Support",
    "Top",
    "Mid Top",
    "Jungle Support",
    "Support",
    "Jungle Top Support",
    "Top Jungle",
    "Top Mid",
    "ADC",
    "ADC",
    "ADC Mid",
    "ADC",
    "Support Mid",
    "Mid Jungle",
    "Mid",
    "Mid",
    "Top Mid",
    "Jungle",
    "Top Mid",
    "Jungle",
    "Jungle",
    "Top",
    "ADC Mid",
    "Mid",
    "Jungle",
    "Support",
    "Jungle Top",
    "Mid",
    "ADC Mid",
    "Support",
    "Mid Support",
    "Top Mid Support",
    "Mid Support",
    "Top Support",
    "Jungle",
    "ADC Support",
    "Top Jungle",
    "Support Mid",
    "Support",
    "Top Jungle",
    "Support",
    "Mid Support",
    "Jungle",
    "Jungle Mid",
    "Jungle Support",
    "Jungle Top",
    "Mid",
    "Top",
    "Top Mid Support",
    "Top Support",
    "Support",
    "Mid Jungle",
    "Top ADC",
    "Support",
    "Jungle",
    "Jungle",
    "Support Jungle",
    "Top",
    "Jungle Top",
    "Top",
    "Top Mid",
    "Mid Top",
    "ADC",
    "Jungle",
    "Support ADC",
    "Mid Support ADC",
    "Top Jungle Support",
    "Jungle Support",
    "Top Support",
    "Jungle",
    "Top",
    "Top Support",
    "ADC",
    "Jungle",
    "Support",
    "Support",
    "Mid Support Top",
    "Mid Top Jungle",
    "Mid ADC",
    "Top Support",
    "Mid Jungle",
    "Mid Jungle",
    "Support",
    "Top Mid Support",
    "Support",
    "ADC Mid",
    "Jungle Top",
    "Top Jungle",
    "Mid",
    "ADC Support Jungle",
    "Jungle",
    "Top",
    "ADC Mid",
    "ADC Top",
    "Mid Support",
    "Mid Support",
    "Jungle",
    "Jungle Top",
    "Mid",
    "Mid Top",
    "Jungle Top",
    "Jungle Top",
    "Top Jungle",
    "ADC",
    "Mid Support",
    "Jungle Top",
    "Mid Top",
    "Mid Top",
    "Top",
    "Support"
]






